question_data = [
    {"type": "multiple", "difficulty": "medium",
     "category": "Entertainment: Television",
     "question": "What is the setting of the show &quot;Parks and Recreation&quot;?",
     "correct_answer": "Pawnee, Indiana",
     "incorrect_answers": ["Eagleton, Indiana", "Pasadena, California", "London, England"]},
    {"type": "multiple", "difficulty": "hard", "category": "Science &amp; Nature",
     "question": "What is the same in Celsius and Fahrenheit?", "correct_answer": "-40",
     "incorrect_answers": ["32", "-39", "-42"]},
    {"type": "multiple", "difficulty": "hard", "category": "Science: Mathematics",
     "question": "Which of these numbers is closest to the total number of possible states for an army standard Enigma Machine?",
     "correct_answer": "1.58 x 10^20", "incorrect_answers": ["1.58 x 10^22", "1.58 x  10^18", "1.58 x 10^24"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "Who published the 1998 video game Half-Life?", "correct_answer": "Sierra On-Line",
     "incorrect_answers": ["Valve", "Blizzard", "EA"]},
    {"type": "multiple", "difficulty": "easy", "category": "Geography",
     "question": "What is the Capital of the United States?", "correct_answer": "Washington, D.C.",
     "incorrect_answers": ["Los Angelas, CA", "New York City, NY", "Houston, TX"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian. ",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "What is the hardest possible difficulty in &quot;Deus Ex: Mankind Divided&quot;?",
     "correct_answer": "I Never Asked For This", "incorrect_answers": ["Nightmare", "Extreme", "Guru"]},
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Film",
     "question": "What was the first monster to appear alongside Godzilla?", "correct_answer": "Anguirus",
     "incorrect_answers": ["King Kong", "Mothra", "King Ghidora"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "Laserjet and inkjet printers are both examples of what type of printer?",
     "correct_answer": "Non-impact printer",
     "incorrect_answers": ["Impact printer", "Daisywheel printer", "Dot matrix printer"]},
    {"type": "multiple", "difficulty": "easy", "category": "Science: Computers",
     "question": "Which SQL keyword is used to fetch data from a database?", "correct_answer": "SELECT",
     "incorrect_answers": ["INDEX", "VALUES", "EXEC"]}]
